package com.socrata.cetera.util

import org.scalatest.{Matchers, FunSuiteLike}

class ElasticsearchErrorSpec extends FunSuiteLike with Matchers {
  test("parse this one error") {
    val thisOneError = "Failed to execute phase [query], all shards failed; shardFailures {[NDfvHsbsQnid-YLZ9_nKGw][201510230201_calendars][0]: SearchParseException[[201510230201_calendars][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [Failed to parse source [{\\\"from\\\":0,\\\"size\\\":100,\\\"query\\\":{\\\"filtered\\\":{\\\"query\\\":{\\\"match_all\\\":{}},\\\"filter\\\":{\\\"and\\\":{\\\"filters\\\":[{\\\"terms\\\":{\\\"socrata_id.domain_cname.raw\\\":[\\\"data.cityofchicago.org\\\"]}},{\\\"not\\\":{\\\"filter\\\":{\\\"terms\\\":{\\\"moderation_status\\\":[\\\"pending\\\",\\\"rejected\\\"]}}}},{\\\"or\\\":{\\\"filters\\\":[]}}]}}}},\\\"sort\\\":[{\\\"page_views.page_views_total\\\":{\\\"order\\\":\\\"desc\\\"}}]}]]]; nested: SearchParseException[[201510230201_calendars][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [No mapping found for [page_views.page_views_total] in order to sort on]]; }{[NDfvHsbsQnid-YLZ9_nKGw][201510230201_charts][0]: SearchParseException[[201510230201_charts][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [Failed to parse source [{\\\"from\\\":0,\\\"size\\\":100,\\\"query\\\":{\\\"filtered\\\":{\\\"query\\\":{\\\"match_all\\\":{}},\\\"filter\\\":{\\\"and\\\":{\\\"filters\\\":[{\\\"terms\\\":{\\\"socrata_id.domain_cname.raw\\\":[\\\"data.cityofchicago.org\\\"]}},{\\\"not\\\":{\\\"filter\\\":{\\\"terms\\\":{\\\"moderation_status\\\":[\\\"pending\\\",\\\"rejected\\\"]}}}},{\\\"or\\\":{\\\"filters\\\":[]}}]}}}},\\\"sort\\\":[{\\\"page_views.page_views_total\\\":{\\\"order\\\":\\\"desc\\\"}}]}]]]; nested: SearchParseException[[201510230201_charts][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [No mapping found for [page_views.page_views_total] in order to sort on]]; }"
    val expectedShortMessage =
      """Failed to execute phase [query], all shards failed;
        |example shard failure:
        |{[NDfvHsbsQnid-YLZ9_nKGw][201510230201_calendars][0]: SearchParseException[[201510230201_calendars][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [Failed to parse source [{\"from\":0,\"size\":100,\"query\":{\"filtered\":{\"query\":{\"match_all\":{}},\"filter\":{\"and\":{\"filters\":[{\"terms\":{\"socrata_id.domain_cname.raw\":[\"data.cityofchicago.org\"]}},{\"not\":{\"filter\":{\"terms\":{\"moderation_status\":[\"pending\",\"rejected\"]}}}},{\"or\":{\"filters\":[]}}]}}}},\"sort\":[{\"page_views.page_views_total\":{\"order\":\"desc\"}}]}]]]; nested: SearchParseException[[201510230201_calendars][0]: query[ConstantScore(+cache(socrata_id.domain_cname.raw:data.cityofchicago.org) +NotFilter(cache(moderation_status:pending moderation_status:rejected)))],from[0],size[100]: Parse Failure [No mapping found for [page_views.page_views_total] in order to sort on]]; }""".stripMargin
    val eem = ElasticsearchError(new Exception(thisOneError))
    eem.shortMessage should be(expectedShortMessage)
  }
}
