FORMAT: 1A

HOST: api.us.socrata.com/api

# Catalog

Main endpoint for querying the catalog of datasets housed by Socrata. Datasets can be found by keywords, domains, high level categorizations, or more granular tags. A given datset may be associated with 0 or more categories or tags. Tags are assigned automatically via stastically derived models; an individual tag may return a confidence value corresponding to model confidence.

Note: select features may not be implemented but are included to future proof the API against version changes.

All calls return a JSON object containing a list of datasets, visualizations, and other assets ranked by relevance in a `results` field. This `results` array contains an array of hashes. Each hash contains a key `resource` containing the resource to be returned. Hashes may contain additional fields to `resource` including metadata about the resource, such as the `classification` object. Each resource is either a page or a dataset.

Datasets and other assets are distinguished by the `type` field.

Multiple components of Socrata's technology stack are represented in the catalog responses. Until the migration from [SODA 2.0 to 2.1](https://dev.socrata.com/changelog/2015/11/25/soda-api-versioning.html) is completed it is necessary to differentiate some requests between the previous (obe) and the current (nbe) stacks. When constructing SODA 2.1 API requests please take care to select the `nbe_fxf` if available, as this is the newer and more performant stack.

With the exception of the additional `type`, `obe_fxf`, and `nbe_fxf` fields, the objects in the `resources` field are unaltered from their representation in whatever owns their truth.

The production API endpoint for the Labs version of this API is `https://api.us.socrata.com/api/catalog/v1`. For example, to query for datasets categorized as `Crime`, you could use the following query:

<a class="tryit" href="http://api.us.socrata.com/api/catalog/v1?categories=public%20safety">http://api.us.socrata.com/api/catalog/v1?categories=public safety</a>

*Please note that we assume that all calls include either the `X-App-Token` header or the ``$$app_token`` parameters set to a valid token. This is assumed and not documented in the API spec below.*

# Search Endpoint [/catalog/v1]

+ Model (application/json)

            {
              "results": [
                {
                "resource" :
                  {
                    "domain" : "data.seattle.gov",
                    "view_count": 3456
                    "description" : "These sensors counts both people riding bikes and pedestrians. Separate volumes are tallied for each travel mode. Wires in a diamond formation in the concrete detect bikes and an infrared sensor mounted on a wooden post detects pedestrians. The counters also capture the direction of travel for both bikes and pedestrians.",
                    "updatedAt" : "2015-02-19T20:01:56.000Z",
                    "type" : "dataset",
                    "id" : "ekqi-b8f3",
                    "obe_fxf" : "ekqi-b8f3",
                    "nbe_fxf" : "3f8b-iqke",
                    "columns" :
                      {
                        "mts_trail_west_of_i_90_bridge_total" :
                          {
                            "name" : "MTS Trail West of I-90 Bridge Total",
                            "description" : ""
                          },
                        ":created_at" : { "name" : ":created_at", "description" : "" },
                        ":updated_at" : { "name" : ":updated_at", "description" : "" },
                        "bike_south" : { "name" : "Bike West", "description" : "" },
                        "ped_north" : { "name" : "Ped East", "description" : "" },
                        ":id" : { "name" : ":id", "description" : "" },
                        "date" : { "name" : "Date", "description" : "" },
                        "bike_north" : { "name" : "Bike East", "description" : "" },
                        "ped_south" : { "name" : "Ped West", "description" : "" },
                        ":version" : { "name" : ":version", "description" : "" }
                      },
                    "name" : "MTS Trail west of I-90 Bridge"
                  },
                  "classification" : {
                    "categories" : ["Transportation"],
                    "tags" : ["transportation"],
                    "domain_categories": ["Things that move"],
                    "domain_tags" : ["planes", "trains", "automobiles"],
                    "domain_metadata" : [
                      {"key": "data-freshness_scope", "value": "daily"},
                      {"key": "manufacturing_vendor", "value": "Boeing"},
                      {"key": "manufacturing_plant-location", "value": "Renton"}
                    ]
                  },
                  "metadata" : { "domain" : "data.seattle.gov" },
                  "link" : "https://data.seattle.gov/ux/dataset/ekqi-b8f3"
                   },
                    {
                "resource" :
                  {
                    "pageId" : "jct9-bvdr",
                    "name" : "Deficiencies",
                    "cards" :
                      [
                        {
                          "fieldName" : "location_state",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "deficiency_prefix",
                          "name" : "",
                          "description" : ""
                        },
                        { "fieldName" : "location", "name" : "", "description" : "" },
                        {
                          "fieldName" : ":@computed_region_4wsx_3rak",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "survey_date",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "deficiency_description",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "survey_type",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "correction_date",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "location_zip",
                          "name" : "",
                          "description" : ""
                        },
                        {
                          "fieldName" : "inspection_cycle",
                          "name" : "",
                          "description" : ""
                        },
                        { "fieldName" : "*", "name" : "", "description" : "" }
                      ],
                    "type" : "page",
                    "datasetId" : "56bb-wjan",
                    "description" : "A list of all deficiencies currently listed on Nursing Home Compare, including the nursing home that received the deficiency, the associated inspection date, deficiency tag number, scope and severity, the current status of the deficiency and the correction date.  Data are presented as one deficiency per row."
                  },
                "classification" : {
                    "categories" : [ "Health" ],
                    "tags" : [ "health" ]
                },
                "metadata" : { "domain" : "data.medicare.gov" },
                "link" : "https://data.medicare.gov/view/jct9-bvdr"
                }
                ],
            "resultSetSize" : 11588,
            "timings" : { "serviceMillis" : 5, "searchMillis" : 5 }
        }




## Searching particular domains [/catalog/v1{?domains,search_context}]
When no `domains` parameter is passed, the search service returns results from the entire corpus.

+ Parameters
    + domains (optional, list[string], `data.seattle.gov,data.hawaii.gov`) ... A comma separated list of cnames. Returns results restricted to only the domains in the list. When not present, searches the entire catalog.
    + search_context (optional, string, `data.seattle.gov`) ... Specifies the domain from where this query was issues and for which categories will be used in search.

### Domain Search API [GET]

+ Response 200

    [Search Endpoint][]

## Searching particular categories [/catalog/v1{?categories}]
When no `categories` parameter is passed, the search service returns results from the entire set of categories.

+ Parameters
    + categories (optional, list[string], `Health,Finance`) ... A comma separated list of categories. Return results restricted to only the categories specified (OR). When not present, searches all categories.

### Category Search API [GET]

+ Response 200

    [Search Endpoint][]

## Full text search [/catalog/v1{?q}]
Full text search will perform a query against all documents in the corpus. Specifically, we will query the fields `name, description, category` as well as the fields representing `column fieldnames, names and description`.

+ Parameters
    + q (optional, string, `chicago crime`) ... A string for full text search

### Full text search API [GET]

+ Response 200

    [Search Endpoint][]


## Pagination [/catalog/v1{?offset,limit}]
The search service allows pagination of results.  By default, we will return at most 100 results starting from 0.
+ Parameters
    + offset (optional, number, `23`) ... Initial starting point for paging (0 by default)
    + limit (optional, number, `47`) ... Number of results to return (100 max/default)

### Pagination API [GET]

+ Response 200

    [Search Endpoint][]


## Limiting results to specific resource types [/catalog/v1{?only}]
The search service currently indexes datasets, visualizations, and other assets with new resource types to be added in the future.  The caller can restrict the results to a particular type (eg `datasets`, `charts`, `maps`) by specifying this parameter.

+ Parameters
    + only (optional, list[string], `datasets`) ... Limit results to a particular resource type (`datasets`, `charts`, `maps`, `datalenses`, `stories`, `files`, `hrefs`). If not present searches all types


### Resource search API [GET]

+ Response 200

    [Search Endpoint][]

## Including additional render metadata  [/catalog/v1{?include_internal_metadata}]
By default (not yet implemented), the search service will only return result data that is useful to a general caller. For the frontend, where additional metadata is stored and may be useful, you can set this flag to true in order to have additional metadata for rendering the dataset or page.

+ Parameters
    + include_internal_metadata (optional, boolean, `true`) ... Results return with additional rendering metadata useful to frontend. If not present, assumed false

### Internal metadata API [GET]

+ Response 200

    [Search Endpoint][]

## Complete Search API [/catalog/v1{?domains,search_context,categories,tags,q,offset,limit,only,include_internal_metadata,highlight}]
The full search API is detailed here, with some additional options such as `tags` and `highlight` which are not yet implemented.

+ Parameters
    + domains (optional, list[string], `cname1,cname2`) ... A comma separated list of cnames. Returns results restricted to only the domains in the list. When not present, searches the entire catalog.
    + search_context (optional, string, `data.seattle.gov`) ... Specifies the domain from where this query was issues and for which categories will be used in search.
    + categories (optional, string, `category1`) ... A single category. Multiple categories may be selected by including multiple instances of this query string parameter. May also be formatted `categories[]=category2`. Return results restricted to only the categories specified (OR). When not present, searches all categories.
    + tags (optional, string, `tag1`) ... A single tag. Multiple tags may be selected by including multiple instances of this query string parameter. May also be formatted `tags[]=tag2`. Return results restricted to only the tags specified (OR). When not present, searches all tags.
    + q (optional, string, `potholes`) ... A string for full text search
    + offset (optional, number, `23`) ... Initial starting point for paging (0 by default)
    + limit (optional, number, `1000`) ... Number of results to return (100 default/max)
    + only (optional, list[string], `datasets`) ... Limit results to a particular resource type (`datasets`, `charts`, `maps`, `datalenses`, `stories`, `files`, `hrefs`). If not present searches all types
    + include_internal_metadata (optional, boolean, `true`) ... Results return with additional rendering metadata useful to frontend. If not present, assumed false
    + highlight (optional, boolean, `true`) ... Include highlighting information

### Search API with all options [GET]

+ Response 200

    [Search Endpoint][]


## Listing Domains [/catalog/v1/domains]
The search service has the ability to return information regarding the domains in its index.
The complete set of query parameters is available to this endpoint as described in the above section.

### Return all domains [GET]

+ Response 200

        {
          "results" :
            [
              { "domain" : "opendata.utah.gov", "count" : 1239 },
              { "domain" : "data.cityofnewyork.us", "count" : 956 },
              { "domain" : "data.illinois.gov", "count" : 491 },
              { "domain" : "data.oregon.gov", "count" : 466 },
              { "domain" : "data.hawaii.gov", "count" : 454 },
              { "domain" : "data.ok.gov", "count" : 423 },
              { "domain" : "data.maryland.gov", "count" : 399 },
              { "domain" : "data.ny.gov", "count" : 391 },
              { "domain" : "www.opendata.go.ke", "count" : 341 },
              { "domain" : "data.cityofchicago.org", "count" : 334 },
              { "domain" : "datacatalog.cookcountyil.gov", "count" : 308 },
              { "domain" : "bronx.lehman.cuny.edu", "count" : 245 },
              { "domain" : "data.colorado.gov", "count" : 238 },
              { "domain" : "data.edmonton.ca", "count" : 238 },
              { "domain" : "data.lacity.org", "count" : 232 },
              { "domain" : "data.mo.gov", "count" : 219 },
              { "domain" : "www.natsdatasct.gob.mx", "count" : 211 },
              { "domain" : "health.data.ny.gov", "count" : 208 },
              { "domain" : "data.ct.gov", "count" : 204 },
              { "domain" : "data.cdc.gov", "count" : 190 },
              { "domain" : "finances.worldbank.org", "count" : 188 },
              { "domain" : "data.medicare.gov", "count" : 186 },
              { "domain" : "data.wa.gov", "count" : 170 },
              { "domain" : "data.baltimorecity.gov", "count" : 167 },
              { "domain" : "data.sfgov.org", "count" : 165 },
              { "domain" : "data.raleighnc.gov", "count" : 139 },
              { "domain" : "data.seattle.gov", "count" : 124 },
              { "domain" : "data.cityofboston.gov", "count" : 123 },
              { "domain" : "data.iowa.gov", "count" : 119 },
              { "domain" : "bythenumbers.sco.ca.gov", "count" : 116 },
              { "domain" : "data.oaklandnet.com", "count" : 114 },
              { "domain" : "data.smcgov.org", "count" : 114 },
              { "domain" : "data.kcmo.org", "count" : 111 },
              { "domain" : "chronicdata.cdc.gov", "count" : 98 },
              { "domain" : "data.cms.gov", "count" : 95 },
              { "domain" : "data.kingcounty.gov", "count" : 90 },
              { "domain" : "data.nola.gov", "count" : 88 },
              { "domain" : "healthdata.nj.gov", "count" : 88 },
              { "domain" : "www.datossct.gob.mx", "count" : 87 },
              { "domain" : "data.nj.gov", "count" : 76 },
              { "domain" : "data.iae.alberta.ca", "count" : 74 },
              { "domain" : "data.michigan.gov", "count" : 69 },
              { "domain" : "data.energystar.gov", "count" : 68 },
              { "domain" : "data.acgov.org", "count" : 61 },
              { "domain" : "data.montgomerycountymd.gov", "count" : 59 },
              { "domain" : "opendata.lasvegasnevada.gov", "count" : 58 },
              { "domain" : "cdph.data.ca.gov", "count" : 57 },
              { "domain" : "data.cambridgema.gov", "count" : 56 },
              { "domain" : "data.melbourne.vic.gov.au", "count" : 51 },
              { "domain" : "controllerdata.lacity.org", "count" : 48 },
              { "domain" : "data.austintexas.gov", "count" : 46 },
              { "domain" : "data.chattlibrary.org", "count" : 45 },
              { "domain" : "data.brla.gov", "count" : 44 },
              { "domain" : "data.winnipeg.ca", "count" : 43 },
              { "domain" : "chhs.data.ca.gov", "count" : 41 },
              { "domain" : "data.cityofberkeley.info", "count" : 40 },
              { "domain" : "data.hartford.gov", "count" : 35 },
              { "domain" : "data.cityofgainesville.org", "count" : 34 },
              { "domain" : "data.datamontana.us", "count" : 34 },
              { "domain" : "data.mass.gov", "count" : 30 },
              { "domain" : "data.awcnet.org", "count" : 27 },
              { "domain" : "data.dcpcsb.org", "count" : 25 },
              { "domain" : "data.providenceri.gov", "count" : 25 },
              { "domain" : "data.strathcona.ca", "count" : 25 },
              { "domain" : "databox.worldbank.org", "count" : 24 },
              { "domain" : "www.dallasopendata.com", "count" : 24 },
              { "domain" : "data.smgov.net", "count" : 22 },
              { "domain" : "data.montgomeryschoolsmd.org", "count" : 21 },
              { "domain" : "data.tol.ca", "count" : 20 },
              { "domain" : "data.texas.gov", "count" : 19 },
              { "domain" : "openpaymentsdata.cms.gov", "count" : 19 },
              { "domain" : "data.nashville.gov", "count" : 16 },
              { "domain" : "data.princegeorgescountymd.gov", "count" : 16 },
              { "domain" : "data.vermont.gov", "count" : 14 },
              { "domain" : "data.murphytx.org", "count" : 12 },
              { "domain" : "data.cityofgp.com", "count" : 11 },
              { "domain" : "data.fortworthtexas.gov", "count" : 9 },
              { "domain" : "data.hampton.gov", "count" : 5 },
              { "domain" : "data.vta.org", "count" : 2 }
            ],
          "timings" : { "serviceMillis" : 5, "searchMillis" : 4 }
        }


## Searching for tags [/catalog/v1/tags]
Returns aggregate tag statistics as well as a list of tags. The compelte set of query functionality is available to this endpoint.


### Return tags [GET]

+ Response 200

        {
          "results" :
            [
              { "tag" : "health", "count" : 1401 },
              { "tag" : "transportation", "count" : 1051 },
              { "tag" : "politics", "count" : 979 },
              { "tag" : "finance", "count" : 917 },
              { "tag" : "business", "count" : 877 },
              { "tag" : "homeless", "count" : 739 },
              { "tag" : "environment", "count" : 587 },
              { "tag" : "crime", "count" : 567 },
              { "tag" : "education", "count" : 467 },
              { "tag" : "construction", "count" : 390 },
              { "tag" : "library", "count" : 171 },
              { "tag" : "infrastructure", "count" : 120 }
            ],
          "timings" : { "serviceMillis" : 4, "searchMillis" : 4 }
        }

## Searching for categories [/catalog/v1/categories]
Returns aggregate category statistics as well as a list of categories.  Complete search functionality is available at this endpoint.


### Return categories [GET]

+ Response 200

        {
          "results" :
            [
              { "category" : "Health", "count" : 1401 },
              { "category" : "Transportation", "count" : 1051 },
              { "category" : "Finance", "count" : 917 },
              { "category" : "Social Services", "count" : 739 },
              { "category" : "Environment", "count" : 587 },
              { "category" : "Public Safety", "count" : 567 },
              { "category" : "Education", "count" : 467 },
              { "category" : "Housing & Development", "count" : 390 },
              { "category" : "Infrastructure", "count" : 390 },
              { "category" : "Recreation", "count" : 171 }
            ],
          "timings" : { "serviceMillis" : 5, "searchMillis" : 4 }
        }

## Listing custom facets [/catalog/v1/domains/{domain}/facets]
Returns a list of domain specific categories, tags, and metadata.

### Return facets [GET]

+ Parameters
    + domain: `data.seattle.gov` (string) - The domain name

+ Response 200 (application/json)

        [
          {
            "facet": "datatypes",
            "count": 1123,
            "values": [
              {"value": "datalens", "count": 17},
              {"value": "dataset", "count": 17},
              {"value": "chart", "count": 17},
              {"value": "map", "count": 17},
              {"value": "calendar", "count": 17},
              {"value": "filter", "count": 17},
              {"value": "href", "count": 17},
              {"value": "file", "count": 17},
              {"value": "form", "count": 17},
            ]
          },
          {
            "facet": "categories",
            "count": 980,
            "values": [
              {"value": "finance", "count": 470},
              {"value": "permits & licenses", "count": 245},
              {"value": "public assets", "count": 123},
              {"value": "public safety", "count": 99},
              {"value": "public services", "count": 42},
              {"value": "transportation" "count": 1}
            ]
          },
          {
            "facet": "tags",
            "count": 70,
            "values": [
              {"value": "youth", "count": 42},
              {"value": "wellbeing", "count": 21},
              {"value": "reportcard" "count": 7}
            ]
          },
          {
            "facet": "data-freshness_scope",
            "count": 170,
            "values": [
              {"value": "all existing and proposed access points", "count": 59},
              {"value": "all existing stations owned by the city of seattle", "count": 48},
              {"value": "all public datasets, filtered views, and visualizations", "count": 37},
              {"value": "all public parking lots in seattle" "count": 26}
            ]
          },
          {
            "facet": "data-freshness_time-period",
            "count": 5,
            "values: [ ... ]
          },
          {
            "facet": "data-freshness_update-frequency",
            "count": 1,
            "values": [ ... ]
          }
        ]
