#!/bin/sh

set -ev

: ${METRICS_DIR:=/tmp/metrics}
export METRICS_DIR

/bin/env_parse /etc/cetera.conf.j2

HEAP_SIZE=${CETERA_HEAP_SIZE:-512m}
GC_LOG_DIR=${MESOS_SANDBOX:-/tmp}

# we do not use the mesos switch_user feature, so the sandbox
# has the wrong permissions, which prevents logs from being
# written by the real (i.e. child) process.
chmod 1777 ${GC_LOG_DIR}

CMD="/usr/bin/java \
  -Dconfig.file=${CETERA_CONFIG} \
  -Xms${HEAP_SIZE} \
  -Xmx${HEAP_SIZE} \
  -Xloggc:${GC_LOG_DIR}/cetera-gc.log \
  -XX:+PrintGCDateStamps \
  -XX:+PrintGCDetails \
  -XX:+PrintGCCause \
  -XX:+PrintTenuringDistribution \
  -XX:+UseGCLogFileRotation \
  -XX:NumberOfGCLogFiles=3 \
  -XX:GCLogFileSize=50M \
  -jar ${CETERA_ROOT}/${CETERA_ARTIFACT}
"

exec su socrata -c "$CMD"
